### ISSUE TITLE
Errore con il plugin YITH WooCommerce Frequently Bought Together Premium

### ISSUE THREAD

**Issue by ideagrafica** [yithemes/yith-woocommerce-wishlist#1]
Nella pagina Lista desideri, in presenza del suddetto plugin, è presente un Warning:  Warning: array_merge(): Argument #2 is not an array in /app/public/wp-content/plugins/yith-woocommerce-frequently-bought-together-premium/templates/yith-wfbt-shortcode.php on line 83.
![Lista Desideri](https://user-images.githubusercontent.com/19994898/67295569-9b33d980-f4e7-11e9-89dd-521a89d2f582.jpg)

**Comment by alarocca130** [comment]
Ciao, grazie per la segnalazione

Sembra un problema collegato a Frenquetly Bought Togheter, e non a Wishlist
Ho passato la tua segnalazione allo sviluppatore, e ci preoccuperemo di rilasciare il fix con il prossimo aggiornamento

Da quello che vedo, lato wishlist, non è richiesta alcuna azione, quindi chiudo il topic
