### ISSUE TITLE
add to cart filter missing in mobile wishlist view

### ISSUE THREAD

**Issue by yordivd** [yithemes/yith-woocommerce-wishlist#12]
yith_wcwl_table_product_show_add_to_cart filter is missing in the wishlist-view-mobile.php
it is available in wishlist-view.php

I think this is an easy fix for you guys. I don't feel like forking and making a PR for something this easy :D

Great plugin!

**Comment by asaldel** [comment]
Hi there.

We have already added the filter in the wishlist-view-mobile.php template and it will be included in the new plugin version we will be releasing today.

Stay tuned to it!
