### ISSUE TITLE
wishlist page keeps loading.

### ISSUE THREAD

**Issue by bassapguy** [yithemes/yith-woocommerce-wishlist#2]
both shortcodes:
[yith_wcwl_wishlist]

[yith_wcwl_wishlist_item]
do not work. i have the premium version, and a custom woocommerce webshop, did i maybe forget something to define

**Comment by alarocca130** [comment]
Hi

This forum regards Wishlist free only
Please, <a href="https://yithemes.com/my-account/support/submit-a-ticket/">submit a ticket</a> to our premium support desk for your issue
