### ISSUE TITLE
non wc products

### ISSUE THREAD

**Issue by Hasan0ff** [yithemes/yith-woocommerce-wishlist#6]
Is it possible to use yith wishlist with custom post types instead of woocommerce product post type?

**Comment by alarocca130** [comment]
Hi

plugin used to support any post type in its early releases; anyway, moving forwad and adding new functionalities over the years, we specialized functions that manage items, and now they can only work with proper WooCommerce products

Unfortunately there is no plan to support CPT as wishlist items; maybe you could consider to fork the project and apply changes needed to make it happen

Finally, a general note: for any question and support request, [wp.org support forum](https://wordpress.org/support/plugin/yith-woocommerce-wishlist/) is a better place to contact us
